### ISSUE TITLE
Issues with terminal wrapping

### ISSUE THREAD

**Issue by 5HT2** [d1snin/resume#1]
My terminal is 86 columns (chars) wide / 44 chars tall, which is the default size on KDE.

```bash
~ ❯ echo -e "lines\ncols" | tput -S
44
86
```

I wouldn't really expect it to wrap around like this.

It works when my terminal is 92 chars wide.

This is *excessive*. There's a reason that 80 chars is used as the universal "width" for line wrapping / cutoffs in code linters, it's because that's the traditional term size.

I'd recommend either
- Reducing the width to fit in 80 chars here. This isn't terribly difficult to do by removing the left padding, which seems unnecessary.
- Or dynamically adjust based on the size of the terminal (this is impossible without a browser as far as I can tell, since curl doesn't provide enough information for the server to determine this).

![image](https://user-images.githubusercontent.com/17222512/160496675-90000df8-b9a2-4b08-bf2c-cd8c32715afb.png)
![image](https://user-images.githubusercontent.com/17222512/160496740-da9fa99c-73ca-432c-9eb1-9c78964357ca.png)

**Comment by d1snin** [comment]
Yeah, that's the issue. `/projects` is the most fat there. 

For the main page, I think I can just replace the banner with some smaller one, and also wrap the text automatically.

In the case of `/projects`, it will be more difficult to make it not so wide. I can remove left and right padding, it is also possible to switch to some more appropriate table format, and, as you already suggested, wrap the text.

**Comment by d1snin** [comment]
![image](https://user-images.githubusercontent.com/68169685/160620704-65852670-7ce1-424c-b953-65734b82e12c.png)

Well, I just removed the padding, table borders and reduced the width of the `shortBio` (it was the main cause) by editing the config file:

```yaml
shortBio: |
  Java/Kotlin software engineer and enthusiast.
  Mostly interested in backend.
```

I'll try to make automated wrapping

**Comment by 5HT2** [comment]
That works much better I think, especially putting the shortBio on multiple lines.

**Comment by d1snin** [comment]
![image](https://user-images.githubusercontent.com/68169685/160716407-af5e1be3-750c-4e7e-8eff-38da6a74296f.png)

I have done automatic lines wrapping. That is, each line should not exceed 60 characters in length.

I'll also bring all pages to the same style and on this issue should be completely resolved.

**Comment by 5HT2** [comment]
Oh huh, that looks much better. Thanks :)

**Comment by d1snin** [comment]
I've written `String.wrapLines()` function for my utility lib recently, and it only works is the text contains whitespaces. 
So, the user can break everything by passing echo without any whitespaces.

- without whitespace:
![image](https://user-images.githubusercontent.com/68169685/160874570-518af374-c010-43f6-97b2-d599c0a4f62a.png)

Also, It will break even if the user provides enough whitespaces in the text, because they are being replaced by `%20` while URL encoding.

There are 2 options:

- remove the `echo` feature at all
- don't use consumed parameters in the pages listing

I prefer the second option

**Comment by d1snin** [comment]
Also, wrapping is not being applied for banners since it may cause unexpected issues.

**Comment by d1snin** [comment]
Just recompiled the app on the server. Changes are available on `https://d1s.dev`
Can you please test it on your machine? @5HT2 
```sh
curl https://d1s.dev/
```

**Comment by 5HT2** [comment]
looks good to me, thanks :)

![Screenshot_20220330-121016](https://user-images.githubusercontent.com/17222512/160881280-7764fbf5-3cd1-461c-be4e-dfa6aad807a5.png)
